auctions/urls.py
from django.urls import path

from . import views

app_name='auction'

urlpatterns = [
    path("", views.index, name="index"), # всі аукціони
    path("", views.index, name="changeCategoryAuction"), # всі аукціони
    path("addWatch/<id>", views.addWatch, name="addWatch"), #  Додавання до списку спостереження
    path("makeRate/<id>/<minRate>", views.makeRate, name="makeRate"), # зробити ставку

    path("addAuction", views.addAuction, name="addAuction"), # додати аукціони
    path("closeAuction/<id>", views.closeAuction, name="closeAuction"), #  Закрити аукціон
    path("active", views.indexActive, name="indexActive"), # активні аукціони
    path("active", views.indexActive, name="changeCategoryActiveAuction"), # Активні аукціони
    path("watch", views.indexWatchList, name="indexWatchList"), # активні аукціони
    path('<id>',views.getAuction,name="getAuction"),
    path("comment/<id>", views.comment, name="comment"), #  Додавання до списку спостереження

]

commerce/urls.py
from django.contrib import admin
from django.contrib.admin.sites import site
from django.http import request
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

app_name = "commerce"

urlpatterns = [
    path("enc/",include("encyclopedia.urls")),
    path("admin/", admin.site.urls),
    path("auction/", include("auctions.urls")),    
    path("mail/", include("mail.urls")),
    path("network/", include("network.urls")),
    path("", include('user.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mail/urls.py
from django.urls import path

from . import views

app_name='mail'

urlpatterns = [
    path("", views.index, name="index"),
    # path("login", views.login_view, name="login"),
    # path("logout", views.logout_view, name="logout"),
    # path("register", views.register, name="register"),

    # API Routes
    path("emails", views.compose, name="compose"),
    path("emails/<int:email_id>", views.email, name="email"),
    path("emails/<str:mailbox>", views.mailbox, name="mailbox"),
]

auctions/models.py
from django.db import models
from django.db.models.deletion import DO_NOTHING
from django.db.models.fields import related
from django.conf import settings


class Categori(models.Model):
    name=models.CharField(max_length=50)

    def __str__(self):
        return f"{self.name}"
    


class Status(models.Model):
    name=models.CharField(max_length=50)

    def __str__(self):
        return f"{self.name}"

class Auction(models.Model):
    name = models.CharField(max_length=150)
    categori=models.ManyToManyField(Categori, blank=True, related_name="categories")
    description=models.TextField()
    first_rate=models.FloatField()
    image=models.ImageField(upload_to='images_auctions/%Y/%m/%d', null=True, blank=True)
    status=models.ForeignKey(Status,on_delete=models.DO_NOTHING)
    createdate= models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING)
    last_rate=models.FloatField(default=0)

    def __str__(self):
        return f"{self.name }, початкова вартість {self.first_rate} ({self.createdate}) - {self.status}"

class AuctionWinner(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING)
    auction=models.ForeignKey(Auction, on_delete=models.DO_NOTHING)
    rate=models.FloatField(default=0)
    date= models.DateTimeField(auto_now_add=True,  blank=True)


class WatchAuction(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    auction = models.ForeignKey(Auction, on_delete=models.DO_NOTHING)

    def __str__(self):
        return f"{self.auction.name} - ({self.user.username})"

class Rates(models.Model):
    auction=models.ForeignKey(Auction,on_delete=models.DO_NOTHING,related_name="rate_auctions")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING)
    rate=models.FloatField()
    date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.auction }, ставка {self.rate} ({self.date})"

class Comments(models.Model):
    auction=models.ForeignKey(Auction,on_delete=models.DO_NOTHING,related_name="auction_comments")
    comment=models.TextField(max_length=255)
    date=models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name="user_comments")

    def __str__(self):
        return f"{self.auction } - {self.comment} ({self.date, self.user})"

auctions/views.py
import os
from django.contrib.auth import authenticate, login, logout, get_user
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.conf import settings
from django.forms import ModelForm
from auctions.models import *
from django.shortcuts import redirect
from django.core.files.storage import FileSystemStorage
from django.contrib import messages




from .models import *

from django.contrib.auth.decorators import login_required

class AuctionForm(ModelForm):
    class Meta:
        model = Auction
        fields = '__all__'
        exclude = ['createdate', 'status', 'user']



def index(request):
    watchList=[]
    if request.user.is_authenticated:
        wList = WatchAuction.objects.filter(user = request.user)
        for el in wList:
            watchList.append(el.auction.id)
    categories = Categori.objects.all()
    if request.method == "POST":
        chooseCat = request.POST['chooseCat'] 
        chooseCatName = "all"
        if chooseCat == "all" :
            auctions = Auction.objects.all()
        else:
            auctions = []
            chooseCatName = Categori.objects.get(id=chooseCat).name
            for auction in Auction.objects.all():
                if len(auction.categori.all().filter(id=chooseCat)) != 0:
                    auctions.append(auction)

        return render(request, "auctions/index.html", {
            'categories':categories,
            'auctions':auctions,
            'currentCat':chooseCatName,
            "active":1,
            "watchList":watchList
        })
    else:
        categories = Categori.objects.all()
        auctions = Auction.objects.all()
        return render(request, "auctions/index.html", {
            'categories':categories,
            'auctions':auctions,
            'currentCat':'all',
            "active":1,
            "watchList":watchList
        })

@login_required()

def indexActive(request):
    watchList=[]
    wList = WatchAuction.objects.filter(user = request.user)
    for el in wList:
        watchList.append(el.auction.id)
    categories = Categori.objects.all()
    if request.method == "POST":
        chooseCat = request.POST['chooseCat'] 
        chooseCatName = "all"
        if chooseCat == "all" :
            auctions = Auction.objects.filter(status="1")
        else:
            auctions = []
            chooseCatName = Categori.objects.get(id=chooseCat).name
            for auction in Auction.objects.filter(status="1"):
                if len(auction.categori.all().filter(id=chooseCat)) != 0:
                    auctions.append(auction)

        return render(request, "auctions/index.html", {
            'categories':categories,
            'auctions':auctions,
            'currentCat':chooseCatName,
            "active":2,
            "watchList":watchList
        })
    else:
        auctions = Auction.objects.filter(status="1")
        return render(request, "auctions/index.html", {
            'categories':categories,
            'auctions':auctions,
            'currentCat':'all',
            "active":2,
            "watchList":watchList
        })

@login_required()

def indexWatchList(request):
    categories = []
    watchList = WatchAuction.objects.filter(user = request.user)
    auctions =[]
    for el in watchList:
        auctions.append(el.auction)
    return render(request, "auctions/index.html", {
            'categories':categories,
            'auctions':auctions,
            'currentCat':'all',
            "active":3,
        })

@login_required()

def addWatch(request,id):
    if request.method == "POST":
        auction = Auction.objects.get(id=id)
        list = WatchAuction.objects.filter(user=request.user, auction = auction)
        if len(list.all()) == 0:
            WatchAuction.objects.create(user=request.user, auction = auction)
        else:
            list.delete()
        return HttpResponseRedirect(reverse('auction:getAuction', kwargs={"id":id}))
    return HttpResponseRedirect(reverse('auction:getAuction', kwargs={"id":id}))


@login_required()

def closeAuction(request,id):
    auction = Auction.objects.get(id=id)
    rates = Rates.objects.filter(auction=auction).order_by('-rate').all()

    if request.method == "POST":
        if auction.user.id == request.user.id:
            if len(rates) != 0:
                auction.status = Status.objects.get(id=2)
                auction.last_rate = rates[0].rate
                auction.save()
                AuctionWinner.objects.create(user = rates[0].user, auction=auction, rate=rates[0].rate)
                if request.user == rates[0].user:
                    messages.info(request, f'Ви виграли у цьому ауціоні. Зв’яжіться з продавцем для отримання товару.') 

        return HttpResponseRedirect(reverse('auction:getAuction', kwargs={"id":id}))

    return HttpResponseRedirect(reverse('auction:getAuction', kwargs={"id":id}))

@login_required()

def makeRate(request,id, minRate):
    if request.method == "POST":
        auction = Auction.objects.get(id=id)
        youRate = request.POST["youRate"]
        if float(youRate) > float(minRate):
            Rates.objects.create(rate=float(youRate), auction=auction, user=request.user)
            auction.last_rate = youRate
            auction.save()
            return HttpResponseRedirect(reverse('auction:getAuction', kwargs={"id":id}))
        else:
            messages.warning(request, f'Ставка має бути більша за {minRate}')    
    return HttpResponseRedirect(reverse('auction:getAuction', kwargs={"id":id}))

@login_required()

def addAuction(request):
    if request.method == "POST" :
        if request.FILES :
            form = AuctionForm(request.POST,  request.FILES)
        else:
            form = AuctionForm(request.POST)
        if form.is_valid() :
            a = Auction()
            a.name = form.cleaned_data['name']
            a.description = form.cleaned_data['description']
            a.first_rate = form.cleaned_data['first_rate']
            a.user=request.user
            a.status=Status.objects.get(id=1)
            a.image=form.cleaned_data['image']
            a.save()
            b = Auction.objects.get(id = a.id)
            b.categori.set(form.cleaned_data['categori'])
            b.save()
            return HttpResponseRedirect(reverse("auction:index"))

        else:
            return render(request, "auctions/add.html", {
            "form": form
            })
    return render(request, "auctions/add.html",{
        "form":AuctionForm,
    })

@login_required()

def comment(request,id):
    if request.method == "POST":
        comment = request.POST["comment"].strip()
        if comment != "":
            auction = Auction.objects.get(id=id)
            Comments.objects.create(comment=comment, auction=auction, user=request.user)
        return HttpResponseRedirect(reverse('auction:getAuction', kwargs={"id":id}))
    return HttpResponseRedirect(reverse('auction:getAuction', kwargs={"id":id}))

def getAuction(request,id):
    auction = Auction.objects.get(id=id)
    categories = auction.categori.all()
    comments = Comments.objects.filter(auction=auction).order_by("-date")
    if request.user.is_authenticated:
        list = WatchAuction.objects.filter(user=request.user, auction = auction)
        if len(list.all()) == 0:
            inWatch = False
        else:
            inWatch = True
        rates = Rates.objects.filter(auction=auction).order_by('-rate').all()
        if len(rates) == 0:
            minRate = auction.first_rate
        else:
            minRate = rates[0].rate
        w = AuctionWinner.objects.filter(auction=auction)
        if len(w.all()) != 0:
            winner =w.all()[0].user
            if winner == request.user:
                messages.info(request, f'Ви виграли у цьому ауціоні. Зв’яжіться з продавцем для отримання товару.') 
        else:
            winner = ''
        return render(request, "auctions/auction.html", {
            'auction':auction,
            'categories':categories,
            'inWatch':inWatch,
            'minRate':minRate,
            'rates':rates,
            "winner": winner,
            "comments": comments
        })
    else:
        return render(request, "auctions/auction.html", {
            'auction':auction,
            'categories':categories,
            "comments": comments,
        })

auctions/templates/auctions/add.html
{% extends "auctions/layout.html" %}
{% block body %}
<h1> Додати новий аукціон</h1>
<form action ="{% url 'auction:addAuction' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
{{form.as_p}}
<button type="submit">Зберегти </button>
</form>
{% endblock %}

auctions/templates/auctions/auction.html
{% extends "auctions/layout.html" %} 

{% block body %}
<div class="col-xs-12">
  <div class="card">
    <div class="card-header">
      <h6 class="card-title">{{auction.name}}</h6>
      {% if user.is_authenticated %}
    <div class="d-inline-flex">
      <form action="{% url 'auction:addWatch' auction.id %}" method="POST"  >
        {% csrf_token %}
        {% if inWatch %}
        <button type="submit" class="btn btn-outline-success">не спостерігати</button>
        {% else %}
        <button type="submit"  class="btn btn-success">спостерігати</button>

        {% endif %}
      </form>
      {% if auction.user.id == user.id%}
        {% if auction.status.id == 1%}
        <form action="{% url 'auction:closeAuction' auction.id %}" method="POST"  >
          {% csrf_token %}
          <button type="submit"  class="btn btn-secondary">Закрити аукціон та визнати переможця</button>

          </form>
        {% endif%}
      {%endif%}

    </div>
      {% endif%}
    </div>
    <div class="row">
      <div class="col-auto" style="display:flex; flex-direction: column;align-items: center;">
        <div style ="position:absolute; left:20px;">
          <h6>{{auction.status}}</h6>
          {% if inWatch %}
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="green" class="bi bi-eyeglasses" viewBox="0 0 16 16">
          <path d="M4 6a2 2 0 1 1 0 4 2 2 0 0 1 0-4zm2.625.547a3 3 0 0 0-5.584.953H.5a.5.5 0 0 0 0 1h.541A3 3 0 0 0 7 8a1 1 0 0 1 2 0 3 3 0 0 0 5.959.5h.541a.5.5 0 0 0 0-1h-.541a3 3 0 0 0-5.584-.953A1.993 1.993 0 0 0 8 6c-.532 0-1.016.208-1.375.547zM14 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0z"/>
        </svg>
        {% endif %}
        </div>
        <div><img
          src="/media/{{auction.image}}"
          class="card-img-top big-picture"
          alt="..."
        />
      </div>
      <div >
        <table style="font-size:12px; width:100%;">
        <tr><th>Створено користувачем: </th> <td>{{auction.user.username}}</td> </tr> 
        <tr><th>Дата створення : </th> <td>{{auction.createdate}}</td> </tr> 
      </table>
      <strong>Категорії</strong>
      {% for categori in categories %}
      <small class="border border-1"><strong> {{categori.name}}</strong></small>
      {% endfor %}
      </div>
      </div>
      <div class="col">
        <strong>Опис </strong>
        <hr />
        <div class="card-text card-description">{{auction.description}}</div>
        <hr />
        <div class=" d-inline-flex">
        <div><strong>Початкова вартість </strong>{{auction.first_rate}} грн.</div>
        <div><strong>Поточна ставка </strong>{{minRate}} грн.</div>
      </div>
      {% if user.is_authenticated %}
        {% if winner == '' %}
        <form action="{% url 'auction:makeRate' auction.id minRate%}" method="POST"  >
          {% csrf_token %}
        <div class="input-group mb-3">
          <input type="number" min={{minRate}} class="form-control" placeholder="Ваша ставка" value={{minRate}} name="youRate">
          <button class="btn btn-outline-secondary" type="submit" >Зробити ставку</button>
        </div>
        
        </form>
        {% else %}

        <div><h1>Переможець : <strong>{{winner}}</strong></h1></div>
        {% endif %}
        {% endif %}
        <div>
          <ul>
          {% for rate in rates %}
          <li>{{rate.user}} {{rate.date}} <strong>{{rate.rate}}</strong></li>
          {% endfor%}
        </ul>
        </div>
      </div>
    </div>
    <div class="card-body">
      <hr />
      <h2> Коментарі</h2>
      {% if user.is_authenticated %}
      <form action="{% url 'auction:comment' auction.id%}" method="POST"  >
        {% csrf_token %}
      <div class="input-group mb-3">
        <input type="textarea" class="form-control" placeholder="текст коментара" name="comment">
        <button class="btn btn-outline-secondary" type="submit" >додати коментар</button>
      </div>
      
      </form>
      {% endif %}
      <table style="font-size:12px;">

      {% for com in comments %}
        <tr><th >{{com.user.username}} </th> <td>{{com.date}}</td> <td>{{com.comment}}</td></tr> 
      {% endfor%}
    </table>
    </div>
  </div>
</div>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link {% if active == 1 %}active {% endif %}" href="{% url 'auction:index' %}">Всі</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {% if active == 2 %}active {% endif %}" href="{% url 'auction:indexActive' %}">Активні</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {% if active == 3 %}active {% endif %}" href="{% url 'auction:indexWatchList' %}">Відстеження</a>
  </li>

</ul>

<a type="button" class="btn btn-outline-success" href="{% url 'auction:addAuction' %}" style="position:absolute; top:20px; right:20px">додати аукціон</a>

{% if active == 1 %}<form action="{% url 'auction:changeCategoryAuction' %}" method="post">{% endif %}
{% if active == 2 %}<form action="{% url 'auction:changeCategoryActiveAuction' %}" method="post">{% endif %}
{% if active == 3 %}<form >{% endif %}
{% if active != 3 %}
  {% csrf_token %}
  <label>Відбір за категорією: </label>
  <select class="form-select" name="chooseCat">
    {% if currentCat == 'all' %}
    
    <option  selected  value='all'>всі категорії</option>
    {% else %}
  <option  value='all'>всі категорії</option>
  {% endif %}
    {% for category in categories %}
    {% if currentCat == category.name %}

    <option value={{category.id}} selected >{{ category.name }}</option>
    {% else %}
    <option value={{category.id}}>{{ category.name }}</option>
    {% endif %}
    {% endfor %}
  </select>

  <button type="submit" class="button">ok</button>
<hr>
{% endif %}
<div class =" d-inline-flex " style="    flex-wrap: wrap;">
{% if not auctions %}
<h1> список порожній </h1>
{% else %} 
  {% for auction in auctions %}
<div class=" col-xs-12 col-md-6 col-xl-3 py-1 px-1">
<div class="card py-1" >
  <div style ="position:absolute; left:10px;">
    <h6>{{auction.status}}</h6>
    {% if user.is_authenticated %}
    {% if auction.id in watchList or active == 3 %}
<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="green" class="bi bi-eyeglasses" viewBox="0 0 16 16">
  <path d="M4 6a2 2 0 1 1 0 4 2 2 0 0 1 0-4zm2.625.547a3 3 0 0 0-5.584.953H.5a.5.5 0 0 0 0 1h.541A3 3 0 0 0 7 8a1 1 0 0 1 2 0 3 3 0 0 0 5.959.5h.541a.5.5 0 0 0 0-1h-.541a3 3 0 0 0-5.584-.953A1.993 1.993 0 0 0 8 6c-.532 0-1.016.208-1.375.547zM14 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0z"/>
</svg>       
    {% endif %}
    {% endif %}
  </div>

    <img src='/media/{{auction.image}}' class="card-img-top big-picture" alt="...">
    <div class="card-body">
      <h6 class="card-title">{{auction.name}}</h6>
      <hr>
      <div class="card-text card-description" ><small>{{auction.description}}</small></div>
      <hr>
      <div><strong>Початкова вартість </strong>{{auction.first_rate}} грн.</div>
      <div><strong>Поточна ставка </strong> {{auction.last_rate}} грн.</div>
      <a href="/auction/{{auction.id}}" class="btn btn-primary full-width">детальна інформація</a>
      <hr>
      {% for categori in auction.categori.all %}
      <small class="border border-1"><strong> {{categori.name}}</strong></small>
      {% endfor %}
    
    </div>
  </div>
</div>
</form>

  {% endfor %}
  {% endif %}
</div>

{% endblock %}

auctions/templates/auctions/layout.html
{% extends "base.html" %}

{% block content %}

{% block body %}
{% endblock %}

{% endblock %}

auctions/templates/auctions/temp.html
{% extends "auctions/layout.html" %}
{% block body %}

{{form}}
{% endblock %}