auctions/urls.py
from django.urls import path

from . import views

app_name='auction'

urlpatterns = [
    path("", views.index, name="index"), # всі аукціони
    path("", views.index, name="changeCategoryAuction"), # всі аукціони
    path("addWatch/<id>", views.addWatch, name="addWatch"), #  Додавання до списку спостереження
    path("makeRate/<id>/<minRate>", views.makeRate, name="makeRate"), # зробити ставку

    path("addAuction", views.addAuction, name="addAuction"), # додати аукціони
    path("closeAuction/<id>", views.closeAuction, name="closeAuction"), #  Закрити аукціон
    path("active", views.indexActive, name="indexActive"), # активні аукціони
    path("active", views.indexActive, name="changeCategoryActiveAuction"), # Активні аукціони
    path("watch", views.indexWatchList, name="indexWatchList"), # активні аукціони
    path('<id>',views.getAuction,name="getAuction"),
    path("comment/<id>", views.comment, name="comment"), #  Додавання до списку спостереження

]

commerce/urls.py
from django.contrib import admin
from django.contrib.admin.sites import site
from django.http import request
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

app_name = "commerce"

urlpatterns = [
    path("enc/",include("encyclopedia.urls")),
    path("admin/", admin.site.urls),
    path("auction/", include("auctions.urls")),    
    path("mail/", include("mail.urls")),
    path("network/", include("network.urls")),
    path("", include('user.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

encyclopedia/urls.py
from django.urls import path

from . import views

app_name ="enc"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:name>",views.article, name="article"),
    path("search/",views.search, name="search"),
    path("add/",views.add, name="add"),
    path("edit/<str:name>",views.edit, name="edit"),
    path("edit",views.saveedit, name="saveedit"),
    path("randompage",views.randompage, name="randompage"),
]

mail/urls.py
from django.urls import path

from . import views

app_name='mail'

urlpatterns = [
    path("", views.index, name="index"),
    # path("login", views.login_view, name="login"),
    # path("logout", views.logout_view, name="logout"),
    # path("register", views.register, name="register"),

    # API Routes
    path("emails", views.compose, name="compose"),
    path("emails/<int:email_id>", views.email, name="email"),
    path("emails/<str:mailbox>", views.mailbox, name="mailbox"),
]

network/urls.py
from django.urls import path

from . import views

app_name='network'


urlpatterns = [
    path("", views.index, name="index"),
]

user/urls.py
from django.urls import path
from . import views

app_name="user"

urlpatterns = [
    path("", views.index, name="index"),
    path('login/', views.login_view, name="login"),
    # path('login/<path>', views.login_view_redirect, name="login_redirect"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register")
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}Auctions{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{% static 'styles.css' %}" rel="stylesheet" />
    {% block script %}

    {% endblock %}
  </head>
  <body>
    <body >
        <!--wrapper-->
      <div class="wrapper toggled">
        <!--start header -->
        <header>

<div class="topbar ">

            <nav class="navbar sticky-top navbar-light shadow rounded">
              <div class ="d-inline-flex">
                <a class="nav-link" href="{% url 'user:index' %}">
                  <img src="../static/favicon.png" class="rounded-circle border border-3 img-thumbnail small-picture" alt="nopic">
                </a>
                <div >
                  <a class="nav-link" href="{% url 'enc:index' %}">Завдання 2. Енциклопедія</a>
                </div>
                <div >
                  <a class="nav-link" href="{% url 'auction:index' %}">Завдання 3. Аукціон </a>
                </div>
                <div >
                  <a class="nav-link border rounded" href="{% url 'mail:index' %}"> Завдання 4. Mail </a>
                </div>
                <div >
                  <a class="nav-link border rounded" href="{% url 'network:index' %}"> Завдання 5. Network </a>
                </div>
              </div>      

            <div class="nav-item ">
              <!--  <div >
                  <a class="nav-link" href="{% url 'enc:index' %}">Енциклопедія</a>
                </div>
                <div >
                  <a class="nav-link" href="{% url 'auction:index' %}">Аукціон </a>
                </div>
              <div >-->
            {% if user.is_authenticated %}
            <div class ="d-inline-flex">
              <a class="nav-link" href="{% url 'user:index' %}">
              {% if request.session.photoUser %}
                <img src={{ request.session.photoUser }} class="small-picture rounded border border-1 img-thumbnail" alt="nopic">
              {% else %}
                <img src="../static/no_user_photo.png" class="small-picture rounded border border-1 img-thumbnail "  alt="nopic">
              {% endif %}
            </a> 

                <div><small>Увійшли як <strong>{{ user.username }}</strong></small>.
                  <a class="nav-link" href="{% url 'user:logout' %}">вийти</a>
                </div>
                </div>
            {% else %}                        <a class="nav-link" href="{% url 'user:login' %}">Увійти</a>
            {% endif %}
            </div>
            </nav>

        </div>
        </header>
        <!--end header -->
        <!--start page wrapper -->
        <div class="page-wrapper">
          <div class="page-content">
            {% if messages %}
          <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
                {% endfor %}
            </div>
            {% endif %}
            {% block content %}

            {% endblock %}

          </div>
        </div>
        <!--end page wrapper -->
        <footer class="page-footer">
			<p class="mb-0">Copyright PalMel© 2021. All right reserved.</p>
		</footer>
    </body>
    <!-- <div class="flex-content">
        <nav class="navbar sticky-top navbar-light shadow rounded column">
          {% if user.is_authenticated %}
          <div>Signed in as <strong>{{ user.username }}</strong>.</div>
          {% else %} Not signed in. {% endif %}
        </nav>
      <div class="row flex-grow-this">
        <div class="container-fluid shadow">
        </div>
      </div>
    </div> -->
  </body>
</html>